appid: "331470"
publishedfileid: "null"         
visibility: "2"               
title: "Яна"
changenote: ""
previewfile: "deploy/avatar.jpg"
project_name: "yn"
exclusions:
  - ".git"
  - ".github"
  - ".gitattributes"
  - ".gitignore"
  - ".vscode"
  - "scripts"
  - "steamcmd"
  - "build"
  - "README.md"
  - "deploy"
  - "exclusions.yml"
  - "markers.yml"