name: Lint ES mod

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: zImpact/es_mod_workflow/.github/workflows/lint_es_mod.yml@v2.0.8
    with:
      project_name: "yn"
      sdk_version: "8.1.3"
      google_drive_id: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver: "1"
      grammar_check_files: code/scenario
      exclusions: "exclusions.yml"
      output_type: "markdown"
      folder: "code"
      markers: "markers.yml"
      run_marker_lint: true
      run_text_lint: true
      run_basic_lint: true